# Base setup
ARG PYTHON_VERSION=3.11.6
ARG DEBIAN_BASE=bookworm
FROM python:${PYTHON_VERSION}-slim-${DEBIAN_BASE} AS base

ARG WKHTMLTOPDF_VERSION=0.12.6.1-3
ARG WKHTMLTOPDF_DISTRO=bookworm
ARG NODE_VERSION=18.18.2
ENV NVM_DIR=/home/frappe/.nvm
ENV PATH=${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/:${PATH}

# Add frappe user and update system packages
RUN useradd -ms /bin/bash frappe && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    curl \
    git \
    vim \
    nginx \
    gettext-base \
    file \
    # weasyprint dependencies
    libpango-1.0-0 \
    libharfbuzz0b \
    libpangoft2-1.0-0 \
    libpangocairo-1.0-0 \
    # For backups
    restic \
    gpg \
    # MySQL client for database access
    mysql-client \
    less \
    # Postgres (if needed for other services)
    libpq-dev \
    postgresql-client \
    # For healthcheck
    wait-for-it \
    jq \
    # NodeJS (using nvm)
    && mkdir -p ${NVM_DIR} && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash && \
    . ${NVM_DIR}/nvm.sh && \
    nvm install ${NODE_VERSION} && \
    nvm use v${NODE_VERSION} && \
    npm install -g yarn && \
    nvm alias default v${NODE_VERSION} && \
    rm -rf ${NVM_DIR}/.cache

# Configure bashrc for nvm
RUN echo 'export NVM_DIR="/home/frappe/.nvm"' >>/home/frappe/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >>/home/frappe/.bashrc && \
    echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >>/home/frappe/.bashrc

# Install wkhtmltopdf with patched qt
RUN if [ "$(uname -m)" = "aarch64" ]; then export ARCH=arm64; fi && \
    if [ "$(uname -m)" = "x86_64" ]; then export ARCH=amd64; fi && \
    downloaded_file=wkhtmltox_${WKHTMLTOPDF_VERSION}.${WKHTMLTOPDF_DISTRO}_${ARCH}.deb && \
    curl -sLO https://github.com/wkhtmltopdf/packaging/releases/download/$WKHTMLTOPDF_VERSION/$downloaded_file && \
    apt-get install -y ./$downloaded_file && \
    rm $downloaded_file

# Clean up APT and add permissions for frappe user
RUN rm -rf /var/lib/apt/lists/* && \
    rm -fr /etc/nginx/sites-enabled/default && \
    pip3 install frappe-bench && \
    sed -i '/user www-data/d' /etc/nginx/nginx.conf && \
    ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log && \
    touch /run/nginx.pid && \
    chown -R frappe:frappe /etc/nginx/conf.d && \
    chown -R frappe:frappe /etc/nginx/nginx.conf && \
    chown -R frappe:frappe /var/log/nginx && \
    chown -R frappe:frappe /var/lib/nginx && \
    chown -R frappe:frappe /run/nginx.pid

COPY resources/nginx-template.conf /templates/nginx/frappe.conf.template
COPY resources/nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh

# Continue with other stages
FROM base AS build

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    wget \
    libffi-dev \
    liblcms2-dev \
    libsasl2-dev \
    libtiff5-dev \
    libwebp-dev \
    redis-tools \
    rlwrap \
    tk8.6-dev \
    cron \
    gcc \
    build-essential \
    libbz2-dev && \
    rm -rf /var/lib/apt/lists/*

USER frappe

# Fetch Frappe and ERPNext source code
FROM build AS builder

ARG FRAPPE_BRANCH=version-15
ARG FRAPPE_PATH=https://github.com/frappe/frappe
ARG ERPNEXT_REPO=https://github.com/frappe/erpnext
ARG ERPNEXT_BRANCH=version-15
RUN bench init \
  --frappe-branch=${FRAPPE_BRANCH} \
  --frappe-path=${FRAPPE_PATH} \
  --no-procfile \
  --no-backups \
  --skip-redis-config-generation \
  --verbose \
  /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  bench get-app --branch=${ERPNEXT_BRANCH} --resolve-deps erpnext ${ERPNEXT_REPO} && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

# Create and configure ERPNext site
ENV SITE_NAME=grierpnext.local
ENV DB_NAME=grierpnext
ENV DB_PASSWORD=oUtuSgbsRrHGYO4!
ENV DB_HOST=grierpnextdb.mysql.database.azure.com
ENV DB_PORT=3306
ENV REDIS_CACHE=redis://grierp-redis.redis.cache.windows.net:6379
ENV REDIS_QUEUE=redis://grierp-redis.redis.cache.windows.net:6379
ENV REDIS_SOCKETIO=redis://grierp-redis.redis.cache.windows.net:6379

RUN cd /home/frappe/frappe-bench && \
    bench new-site $SITE_NAME \
    --db-name $DB_NAME \
    --db-password $DB_PASSWORD \
    --admin-password admin \
    --mariadb-root-password $DB_PASSWORD && \
    # Update site_config.json with database and Redis configurations
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json db_type "mysql" && \
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json db_host "$DB_HOST" && \
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json db_port "$DB_PORT" && \
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json redis_cache "$REDIS_CACHE" && \
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json redis_queue "$REDIS_QUEUE" && \
    bench set-config -c /home/frappe/frappe-bench/sites/$SITE_NAME/site_config.json redis_socketio "$REDIS_SOCKETIO"

FROM base AS erpnext

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/sites/assets", \
  "/home/frappe/frappe-bench/logs" \
]

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]
